// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"core/models"
)

func newDataSource(db *gorm.DB, opts ...gen.DOOption) dataSource {
	_dataSource := dataSource{}

	_dataSource.dataSourceDo.UseDB(db, opts...)
	_dataSource.dataSourceDo.UseModel(&models.DataSource{})

	tableName := _dataSource.dataSourceDo.TableName()
	_dataSource.ALL = field.NewAsterisk(tableName)
	_dataSource.ID = field.NewField(tableName, "id")
	_dataSource.OrgID = field.NewField(tableName, "org_id")
	_dataSource.TeamID = field.NewField(tableName, "team_id")
	_dataSource.Type = field.NewString(tableName, "type")
	_dataSource.Name = field.NewString(tableName, "name")
	_dataSource.Credentials = field.NewString(tableName, "credentials")
	_dataSource.Visibility = field.NewString(tableName, "visibility")
	_dataSource.CreatedAt = field.NewTime(tableName, "created_at")

	_dataSource.fillFieldMap()

	return _dataSource
}

type dataSource struct {
	dataSourceDo

	ALL         field.Asterisk
	ID          field.Field
	OrgID       field.Field
	TeamID      field.Field
	Type        field.String
	Name        field.String
	Credentials field.String
	Visibility  field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (d dataSource) Table(newTableName string) *dataSource {
	d.dataSourceDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataSource) As(alias string) *dataSource {
	d.dataSourceDo.DO = *(d.dataSourceDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataSource) updateTableName(table string) *dataSource {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewField(table, "id")
	d.OrgID = field.NewField(table, "org_id")
	d.TeamID = field.NewField(table, "team_id")
	d.Type = field.NewString(table, "type")
	d.Name = field.NewString(table, "name")
	d.Credentials = field.NewString(table, "credentials")
	d.Visibility = field.NewString(table, "visibility")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *dataSource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataSource) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 8)
	d.fieldMap["id"] = d.ID
	d.fieldMap["org_id"] = d.OrgID
	d.fieldMap["team_id"] = d.TeamID
	d.fieldMap["type"] = d.Type
	d.fieldMap["name"] = d.Name
	d.fieldMap["credentials"] = d.Credentials
	d.fieldMap["visibility"] = d.Visibility
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d dataSource) clone(db *gorm.DB) dataSource {
	d.dataSourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataSource) replaceDB(db *gorm.DB) dataSource {
	d.dataSourceDo.ReplaceDB(db)
	return d
}

type dataSourceDo struct{ gen.DO }

type IDataSourceDo interface {
	gen.SubQuery
	Debug() IDataSourceDo
	WithContext(ctx context.Context) IDataSourceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataSourceDo
	WriteDB() IDataSourceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataSourceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataSourceDo
	Not(conds ...gen.Condition) IDataSourceDo
	Or(conds ...gen.Condition) IDataSourceDo
	Select(conds ...field.Expr) IDataSourceDo
	Where(conds ...gen.Condition) IDataSourceDo
	Order(conds ...field.Expr) IDataSourceDo
	Distinct(cols ...field.Expr) IDataSourceDo
	Omit(cols ...field.Expr) IDataSourceDo
	Join(table schema.Tabler, on ...field.Expr) IDataSourceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataSourceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataSourceDo
	Group(cols ...field.Expr) IDataSourceDo
	Having(conds ...gen.Condition) IDataSourceDo
	Limit(limit int) IDataSourceDo
	Offset(offset int) IDataSourceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataSourceDo
	Unscoped() IDataSourceDo
	Create(values ...*models.DataSource) error
	CreateInBatches(values []*models.DataSource, batchSize int) error
	Save(values ...*models.DataSource) error
	First() (*models.DataSource, error)
	Take() (*models.DataSource, error)
	Last() (*models.DataSource, error)
	Find() ([]*models.DataSource, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DataSource, err error)
	FindInBatches(result *[]*models.DataSource, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.DataSource) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataSourceDo
	Assign(attrs ...field.AssignExpr) IDataSourceDo
	Joins(fields ...field.RelationField) IDataSourceDo
	Preload(fields ...field.RelationField) IDataSourceDo
	FirstOrInit() (*models.DataSource, error)
	FirstOrCreate() (*models.DataSource, error)
	FindByPage(offset int, limit int) (result []*models.DataSource, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataSourceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataSourceDo) Debug() IDataSourceDo {
	return d.withDO(d.DO.Debug())
}

func (d dataSourceDo) WithContext(ctx context.Context) IDataSourceDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataSourceDo) ReadDB() IDataSourceDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataSourceDo) WriteDB() IDataSourceDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataSourceDo) Session(config *gorm.Session) IDataSourceDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataSourceDo) Clauses(conds ...clause.Expression) IDataSourceDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataSourceDo) Returning(value interface{}, columns ...string) IDataSourceDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataSourceDo) Not(conds ...gen.Condition) IDataSourceDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataSourceDo) Or(conds ...gen.Condition) IDataSourceDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataSourceDo) Select(conds ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataSourceDo) Where(conds ...gen.Condition) IDataSourceDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataSourceDo) Order(conds ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataSourceDo) Distinct(cols ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataSourceDo) Omit(cols ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataSourceDo) Join(table schema.Tabler, on ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataSourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataSourceDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataSourceDo) Group(cols ...field.Expr) IDataSourceDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataSourceDo) Having(conds ...gen.Condition) IDataSourceDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataSourceDo) Limit(limit int) IDataSourceDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataSourceDo) Offset(offset int) IDataSourceDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataSourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataSourceDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataSourceDo) Unscoped() IDataSourceDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataSourceDo) Create(values ...*models.DataSource) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataSourceDo) CreateInBatches(values []*models.DataSource, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataSourceDo) Save(values ...*models.DataSource) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataSourceDo) First() (*models.DataSource, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.DataSource), nil
	}
}

func (d dataSourceDo) Take() (*models.DataSource, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.DataSource), nil
	}
}

func (d dataSourceDo) Last() (*models.DataSource, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.DataSource), nil
	}
}

func (d dataSourceDo) Find() ([]*models.DataSource, error) {
	result, err := d.DO.Find()
	return result.([]*models.DataSource), err
}

func (d dataSourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DataSource, err error) {
	buf := make([]*models.DataSource, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataSourceDo) FindInBatches(result *[]*models.DataSource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataSourceDo) Attrs(attrs ...field.AssignExpr) IDataSourceDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataSourceDo) Assign(attrs ...field.AssignExpr) IDataSourceDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataSourceDo) Joins(fields ...field.RelationField) IDataSourceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataSourceDo) Preload(fields ...field.RelationField) IDataSourceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataSourceDo) FirstOrInit() (*models.DataSource, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.DataSource), nil
	}
}

func (d dataSourceDo) FirstOrCreate() (*models.DataSource, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.DataSource), nil
	}
}

func (d dataSourceDo) FindByPage(offset int, limit int) (result []*models.DataSource, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataSourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataSourceDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataSourceDo) Delete(models ...*models.DataSource) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataSourceDo) withDO(do gen.Dao) *dataSourceDo {
	d.DO = *do.(*gen.DO)
	return d
}
